### ISSUE TITLE
MedicationRequest mapping is broken

### ISSUE THREAD

**Issue by MiskoG** [arkhn-oss/Cohort360#42]
#### Description  ⁉️
Le mapping est cassé dans `dosageInstruction.doseAndRate.doseQuantity.value` --> parfois c'est une range (quand y'a un `-` dans la value) donc ça plante au loading dans hapi (reproductible dans la preview pyrog).

#### Comment reproduire  🗺
- Pyrog demoet --> MedicationRequest -> preview sur table "prescriptions" avecv une range

#### Le sauveur  👨🏻‍🚒
- Nico <3

**Comment by nriss** [comment]
I see two possibilities:
- create a script to remove the intervals from db (take the first value for instance)
- create two cleaning scripts to get 1. the first value 2. the second value and then add it to dose[x].doseRange using a condition in case it is an interval, or dose[x].doseQuantity otherwise

The second point seems complex because:
- Have to create two cleaning scripts which are really specific-usage (@elsiehoffet-94 what do you think of that ?)
- Have to redeploy cleaning scripts on demo
- Have to create a condition "contains" that doesn't exist on pyrog for now to say: `include/exclude if the value contains '-'` (@Jasopaum what do you think of adding that kind of condition ? Could be interesting for the new pyrog according to me).
- Have to adapt cohort360 front to take into account doseRange

I think I will go on the first option and work on that tomorrow, which looks to be the simplest.

I will also take this opportunity to modify by hand the d_* tables to correct automatic translation errors

**Comment by nriss** [comment]
SQL command to remove intervals and only keep the first number:

```
UPDATE prescriptions 
	SET dose_val_rx = regexp_replace(dose_val_rx, '-[0-9]+', '') 
	WHERE dose_val_rx LIKE '%-%';
```

This SQL request should be lauched every time we regenerate the db

**Comment by elsiehoffet-94** [comment]
@nriss I agree that doing it in the db generation is the best way to proceed 👍

**Comment by nriss** [comment]
@simonvadee  can we close this issue ?

And these ?
https://github.com/arkhn/Cohort360/issues/40
https://github.com/arkhn/Cohort360/issues/41

**Comment by simonvadee** [comment]
yes!
