### ISSUE TITLE
As a user I can see the diagnosis codes and search them when adding a diagnosis cohort criteria

### ISSUE THREAD

**Issue by elsiehoffet-94** [arkhn-oss/Cohort360#93]
## Problème
Dans l'ajout de critères pour créer une cohorte, dans PMSI> Diagnostics, il faudrait pouvoir choisir parmi les codes de la CIM-10, (aujourd'hui CIM-9 uniquement). Il faudrait aussi pouvoir rechercher par code et pas par libellé uniquement.  

## Description
Ce que ça implique : 
- Créer/ajouter un ValueSet CIM-10, et peut être un ValueSet qui regroupe CIM-10, CIM-9 @nriss tu en penses quoi?
- Modifier l'interface : pouvoir faire le choix de la classif? Ou bien avoir une barre de recherche regroupant les deux ensembles de codes? 
- Modifier le texte affiché (aujourd'hui il y a écrit CIM-9 au niveau de l'ajout de critère, puis CIM-10 une fois le critère ajouté)
- Pouvoir rechercher un diagnostic CIM-* en fonction de son code, ou de son libellé (aujourd'hui uniquement possible avec le libellé, pas le code)
- (Typo) Diagnosti**c** pour le substantif et diagnosti**que** pour l'adjectif

## Contexte
Remarques soulevées par @Peltier10

**Comment by elsiehoffet-94** [comment]
linked to #94

**Comment by nriss** [comment]
Originally, Cohort360 has been developed using mimic-iii, which uses icd-9 classification!
I think it's just hard written 'icd-9', there is just a text correction to do, maybe replace by 'icd-9/icd-10 code', 'Condition code', 'Code pathologie' or something like that

I think we are just looking on the `code` search param of the Condition resource without regarding any system. And according to me, today, we can search using the code but not the display ? (@tevariou is it right ?)

We can create 3 VS:
- a VS icd-10
- a VS icd-9,
- a VS that concatenates the two (see ValueSet.compose.include.valueSet)
However, I don't think icd-9 is used anymore in France, but we can keep the choice of multiple terminologies (icd-11 arriving..) 

On the page, it could be cool to have a textbox / multiple selectbox with an autocomplete to choose among all pathology terminologies

**Comment by elsiehoffet-94** [comment]
Thanks a lot for this clarification, it's much clearer :)

> I think we are just looking on the code search param of the Condition resource without regarding any system. And according to me, today, we can search using the code but not the display ? (@tevariou is it right ?)

Today, it's only possible to select an item from the dropdown, but the front does not allow typing a code. I think we should fix this in the front, without waiting for any design decision at this point.

We should definitely keep multiple terminologies, and discuss a bit more about the best way to handle those with @MiskoG . I don't think a comprehensive valueSet is the most appropriate way for ICD-*, it means creating a valueSet of >16K codes.

**Comment by MiskoG** [comment]
Indeed, as a reminder today it works like this

![image](https://user-images.githubusercontent.com/7942024/119514190-1bca5400-bd75-11eb-823c-530464518173.png)

- Front says that you have to choose only among ICD-9 codes
- You can search among those codes and select one or more of them (in fact, among the sublist of codes included in the corresponding ValueSet)
- Once selected, a small UI bug : it says that these are ICD-10 codes (even if they are not)

➡️  We can put whatever codes we want in our ValueSet. 
So maybe we could handle the situation this way, as long as there is only one terminology used for diagnosises :

- We fill our ValueSet ressource with the codes and terminology that are relevant for the center - in Toulouse, it would be some ICD-10 codes (you may have already done this @nriss)
- Then in front, we could just look into this ValueSet (without saying explicitly in front this is ICD-9 or ICD-10) and add the codes in front of each element. For instance, instead of writing "Tumeur lipomateuse bénigne de la peau et du tissu sous-cutané du tronc" we say "**D17.1** - Tumeur lipomateuse bénigne de la peau et du tissu sous-cutané du tronc" so that the user can search a specific element by his code or display.

![image](https://user-images.githubusercontent.com/7942024/119532327-12e17e80-bd85-11eb-8ef2-0c617fa2a0a9.png)

As long as there is only one terminology (or ValueSet) used this solution works. When we will have multiple terminologies, then I guess the solution will be a bit more complex.

What do you guys think @elsiehoffet-94 @nriss ?

**Comment by nriss** [comment]
A ValueSet containing all icd-10 codes called CohortConditionsVS has been added to the cohort360 ig (discussed with @tevariou )

**Comment by MiskoG** [comment]
Right, so maybe the first implementation would be to "just" link the frontend to this _CohortConditionsVS_, and then also add the code of each element of the ValueSet so that it is shown to the user and is searchable.

**Comment by nriss** [comment]
Totally agree with you @MiskoG !

For now, we can add all icd-10 codes for now and then adapt to a subset of codes if needed by the current situation

**Comment by MiskoG** [comment]
I'm still a bit confused about how to show the code (D17.1 for instance) of each element in front.
I guess it is directly written in the ValueSet for each element, or in the original CodeSystem ?

**Comment by nriss** [comment]
The [CodeSystem](https://terminology.hl7.org/2.0.0/CodeSystem-icd10.html) define the terminology but does not necessarily contain the codes 
The expanded ValueSet contain all codes and display, as shown in this [expansion array](https://build.fhir.org/valueset-icd-10.html#expansion)

According to me, it could be cool to show both code and display as you said

**Comment by MiskoG** [comment]
Ok great :) 

Also, when we need to adjust the ValueSet linked to Cohort, should we have some sort of config file to do that ? In order to not modify Cohort code directly in each center

**Comment by nriss** [comment]
It would be so cool to give the possibility to change the ValueSet.url of the desired VS on cohort settings!

In that case, if we want to change the VS, we will just have to:
- create a new VS (using FSH for example)
- Push it into hapifhir
- change the VS url on cohort360 settings

and it works! 🚀

**Comment by MiskoG** [comment]
Alright so I created an issue for that.
I suggest that in this current issue, we just focus on displaying the codes to the user and being able to search them 🔍

**Comment by MiskoG** [comment]
@tevariou Do you want to take this one ? I'm available to clarify stuff if needed

**Comment by tevariou** [comment]
@MiskoG yep!
